#!/bin/sh
#
# Hook script which prepends the commit message with the current branch.

BRANCH_NAME=$(git symbolic-ref --short HEAD)
if [[ $BRANCH_NAME == feature/* ]] || [[ $BRANCH_NAME == hotfix/* ]]; then
    if grep -vq "\[[A-Za-z]*-[0-9]*\]" <<< $BRANCH_NAME; then 
        TICKET_NUMBER=$(sed 's/.*\///' <<< $BRANCH_NAME)
        sed -i.bak -e "s/^/[$TICKET_NUMBER]\ /" $1
    fi
fi
